services:
  - type: web
    name: capstone-project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn capstone_project.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: capstone-db
          property: connectionString

databases:
  - name: capstone-db
    plan: free
