services:
  - type: web
    name: your-project-name
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"